export type IScreens =
  | 'home'
  | 'start'
  | 'signin'
  | 'signup'
  | 'services'
  | 'events'
  | 'eventdetail'
  | 'newevent'
  | 'detail'
  | 'profile'
  | 'editprofile'
  | 'passwordrecover'
